# Generated by Django 2.0.3 on 2018-03-30 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processdata',
            old_name='Engine_efficiency',
            new_name='engine_efficiency',
        ),
        migrations.RenameField(
            model_name='processdata',
            old_name='green_Value',
            new_name='green_value',
        ),
        migrations.RenameField(
            model_name='processdata',
            old_name='Pulsometer_readout',
            new_name='pulsometer_readout',
        ),
        migrations.RenameField(
            model_name='processdata',
            old_name='red_Value',
            new_name='red_value',
        ),
        migrations.RenameField(
            model_name='processdata',
            old_name='time_stamp',
            new_name='timestamp',
        ),
    ]
