# Generated by Django 2.0.3 on 2018-03-30 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180330_1128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcessData',
            new_name='DashboardData',
        ),
        migrations.RenameField(
            model_name='dashboarddata',
            old_name='blue_Value',
            new_name='blue_value',
        ),
    ]
