# Generated by Django 2.0.3 on 2018-03-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180330_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='pulsometer_readout',
            field=models.FloatField(),
        ),
    ]
